// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/generate.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/GaugeChart.tsx";
import * as $$1 from "./islands/LineChart.tsx";
import * as $$2 from "./islands/Loading.tsx";
import * as $$3 from "./islands/PieChart.tsx";
import * as $$4 from "./islands/ResultsView.tsx";
import * as $$5 from "./islands/StaticView.tsx";
import * as $$6 from "./islands/UploadView.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/generate.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/GaugeChart.tsx": $$0,
    "./islands/LineChart.tsx": $$1,
    "./islands/Loading.tsx": $$2,
    "./islands/PieChart.tsx": $$3,
    "./islands/ResultsView.tsx": $$4,
    "./islands/StaticView.tsx": $$5,
    "./islands/UploadView.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
